name: C/C++ CI - TRBBFI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [release, debug, profile]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential clang-format cppcheck

    - name: Set build configuration
      run: echo "BUILD_CONFIG=${{ matrix.config }}" >> $GITHUB_ENV

    - name: Build
      run: make ${{ matrix.config }}

    - name: Run Tests
      run: make test

    - name: Strip binary (release only)
      if: matrix.config == 'release'
      run: make strip

    - name: Show build info
      run: make info
